version: '3.4'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
  node:
    container_name: node
    build: .
    ports:
      - '${PORT}:3000'
    depends_on:
      - redis
    env_file: .env